apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: {{ .Values.orderService.type }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: order-service