apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-service
spec:
  type: {{ .Values.rabbitmq.type }}
  selector:
    app: {{ include "rabbitmq.fullname" . }}-service
  ports:
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672
    - name: rabbitmq-http
      port: 15672
      targetPort: 15672