apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: product-service
  type: '{{ .Values.productService.type }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - env:
        - name: AI_SERVICE_URL
          value: http://ai-service:5001/
        image: '{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag
          }}'
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
        name: product-service
        ports:
        - containerPort: 3002
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            cpu: 2m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 1Mi
      nodeSelector:
        kubernetes.io/os: linux
