apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-front.fullname" . }}-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: {{ include "store-front.fullname" . }}-service
  type: {{ .Values.storeFront.type }}