apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rabbitmq.fullname" . }}-service
  labels:
  {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ include "rabbitmq.fullname" . }}-service
  template:
    metadata:
      labels:
        app: {{ include "rabbitmq.fullname" . }}-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ include "rabbitmq.fullname" . }}-service
          image: mcr.microsoft.com/azurelinux/base/rabbitmq-server:3.13
          ports:
            - containerPort: 5672
              name: rabbitmq-amqp
            - containerPort: 15672
              name: rabbitmq-http
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "username"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: rabbitmq-enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
      volumes:
        - name: rabbitmq-enabled-plugins
          configMap:
            name: rabbitmq-enabled-plugins
            items:
              - key: rabbitmq_enabled_plugins
                path: enabled_plugins